<template>
    <div class="loadingio-spinner-spinner-48yxq40kek6" :style="{ scale: scale }">
        <div class="ldio-hobingjbrfi">
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>
</template>

<script>
export default {
    props: {
        color: {
            type: String,
            default: '#23262f'
        },
        scale: {
            type: Number,
            default: 1
        }
    },
    mounted() {
        // Thiết lập CSS variable cho màu sắc
        this.$el.style.setProperty('--loader-color', this.color)
    },
    watch: {
        // Watch để cập nhật màu khi prop thay đổi
        color(newColor) {
            this.$el.style.setProperty('--loader-color', newColor)
        }
    }
}
</script>

<style type="text/css">
@keyframes ldio-hobingjbrfi {
    0% {
        opacity: 1;
    }
    100% {
        opacity: 0;
    }
}
.ldio-hobingjbrfi div {
    left: 47px;
    top: 24px;
    position: absolute;
    animation: ldio-hobingjbrfi linear 1s infinite;
    width: 6px;
    height: 12px;
    border-radius: 3px / 6px;
    transform-origin: 3px 26px;
}
/* Sử dụng CSS var() để áp dụng màu động */
.ldio-hobingjbrfi div {
    background: var(--loader-color);
}
.ldio-hobingjbrfi div:nth-child(1) {
    transform: rotate(0deg);
    animation-delay: -0.9166666666666666s;
}
.ldio-hobingjbrfi div:nth-child(2) {
    transform: rotate(30deg);
    animation-delay: -0.8333333333333334s;
}
.ldio-hobingjbrfi div:nth-child(3) {
    transform: rotate(60deg);
    animation-delay: -0.75s;
}
.ldio-hobingjbrfi div:nth-child(4) {
    transform: rotate(90deg);
    animation-delay: -0.6666666666666666s;
}
.ldio-hobingjbrfi div:nth-child(5) {
    transform: rotate(120deg);
    animation-delay: -0.5833333333333334s;
}
.ldio-hobingjbrfi div:nth-child(6) {
    transform: rotate(150deg);
    animation-delay: -0.5s;
}
.ldio-hobingjbrfi div:nth-child(7) {
    transform: rotate(180deg);
    animation-delay: -0.4166666666666667s;
}
.ldio-hobingjbrfi div:nth-child(8) {
    transform: rotate(210deg);
    animation-delay: -0.3333333333333333s;
}
.ldio-hobingjbrfi div:nth-child(9) {
    transform: rotate(240deg);
    animation-delay: -0.25s;
}
.ldio-hobingjbrfi div:nth-child(10) {
    transform: rotate(270deg);
    animation-delay: -0.16666666666666666s;
}
.ldio-hobingjbrfi div:nth-child(11) {
    transform: rotate(300deg);
    animation-delay: -0.08333333333333333s;
}
.ldio-hobingjbrfi div:nth-child(12) {
    transform: rotate(330deg);
    animation-delay: 0s;
}
.loadingio-spinner-spinner-48yxq40kek6 {
    width: 30px;
    height: 30px;
    display: inline-block;
    overflow: hidden;
    background: none;
}
.ldio-hobingjbrfi {
    width: 100%;
    height: 100%;
    position: relative;
    transform: translateZ(0) scale(0.3);
    backface-visibility: hidden;
    transform-origin: 0 0;
}
.ldio-hobingjbrfi div {
    box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
